### ISSUE TITLE
Printing error

### ISSUE THREAD

**Issue by Klara-Marie** [eliasweingaertner/peripage-A6-bluetooth#8]
I get this error when i try to print my image:

```
klara@raspberrypi:~/peripage-A6-bluetooth $ ./ppa6-print.py -i image.jpg 20:21:01:38:FF:C9
Traceback (most recent call last):
  File "/home/klara/peripage-A6-bluetooth/./ppa6-print.py", line 2, in <module>
    import bluetooth
  File "/home/klara/.local/lib/python3.9/site-packages/bluetooth/__init__.py", line 45, in <module>
    from bluetooth.bluez import *
  File "/home/klara/.local/lib/python3.9/site-packages/bluetooth/bluez.py", line 8, in <module>
    import bluetooth._bluetooth as _bt
ImportError: libbluetooth.so.3: cannot open shared object file: No such file or directory
```
Why is that? should the image be saved somewhere specific?

**Comment by Klara-Marie** [comment]
im a beginner and I installed it wrong but now it works
